{% set name = "spymicmac" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f05b3c9b8948433e2a94d3b9416b59ea2ebcc68f49396f2e9781b3e08e508900

build:
  noarch: python
  entry_points:
    - balance_images = spymicmac.tools.balance_images:main
    - combine_auto_measures = spymicmac.tools.combine_auto_measures:main
    - find_reseau_grid = spymicmac.tools.find_reseau_grid:main
    - generate_micmac_measures = spymicmac.tools.generate_micmac_measures:main
    - join_hexagon = spymicmac.tools.join_hexagon:main
    - move_bad_tapas = spymicmac.tools.move_bad_tapas:main
    - register_ortho = spymicmac.tools.register_ortho:main
    - remove_crosses = spymicmac.tools.remove_crosses:main
    - remove_measures = spymicmac.tools.remove_measures:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - earthengine-api
    - gdal
    - geopandas
    - lxml
    - matplotlib-base
    - numpy
    - opencv
    - pandas
    - pyasn1
    - pybob >=0.26.2
    - pymmaster >=0.1.1
    - python >=3.7
    - scikit-image >=0.18
    - scipy
    - shapely
    - sphinx-argparse
    - usgs

test:
  imports:
    - spymicmac
  requires:
    - pip

about:
  home: https://github.com/iamdonovan/sPyMicMac
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: a python package for processing KH-9 imagery using MicMac
  doc_url: https://spymicmac.readthedocs.io

extra:
  recipe-maintainers:
    - iamdonovan
